# The name of this app must be unique within this project.
name: examplesite

# Which php version to use on the app server. (or use 'none')
php: none

# The type of application as accepted by podium.
type: html

# Enable required PHP extensions.
extensions:
  build:
    - mcrypt
    - json
  run:
    - redis

# The webserver configuration for your application.
web:
  locations:
    "/":
      docroot: "/public" # The public directory of the app, relative to the app root.
      controller: "/index.php" # The controller file to handle the request dynamically.
    "/files":
      docroot: "/storage/app/public"

# The files or directories to preserve between builds (uploads, logs or config files).
mounts:
  - .env
  - storage

# Build, deployment and release hooks.
hooks:
  # Build hook is executed on the worker server.
  build: |
    echo 'My awesome build!'
    date
    echo '123 My awesome build just finished...'
  # Deploy hook is executed on the app server, allowing for database access.
  deploy: |
    echo 'Deploy script...'
  # The commands necessary to release your application to the public.
  release: |
    echo 'Release script...'

# Your application's required cronjobs.
crons:
  "touch": # Pick a name for this cron.
    schedule: "* * * * *"
    command: "/usr/bin/touch ~/myfile"

# Daemons are persisted with supervisor.
daemons:
  "queue-worker":
    command: "/usr/bin/watch -n 30 df -h"

# Set any environment variable during build.
env:
  EXAMPLE_PARAM: 'example-param'
